export default [
  {
    From: "다부처",
    workedat: "우리씨앤씨",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image:"https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Fscreenshot01.png?alt=media&token=48982727-0211-4ea5-af14-8693de42b9e3",
    Percentage: "100",
    Title: "공공문화데이터광장",
    Html: "<div class='title'>작성중</div>",
    id: 0,
  },
  {
    From: "다부처",
    workedat: "우리씨앤씨",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image: "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Fscreenshot02.png?alt=media&token=17a8d8c4-bbef-4cdc-aa9d-7a60613fbe9e",
    Percentage: "100",
    Title: "공공문화데이터광장 - 챗봇 서비스",
    Html: "<div class='title'>작성중</div>",
    id: 0,
  },
  {
    From: "대한항공",
    workedat: "이원정보통신",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image: "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Fscreenshot03.png?alt=media&token=cc6dfda7-aec8-46fe-9343-64c18e0e9ac0",
    Percentage: "100",
    Title: "대한항공 내부시스템 운영 및 유지보수",
    id: 1,
    Html: "<div class='title'>작성중</div>",
  },
  {
    From: "대한항공",
    workedat: "이원정보통신",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image: "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Fscreenshot03.png?alt=media&token=cc6dfda7-aec8-46fe-9343-64c18e0e9ac0",
    Percentage: "40",
    Title: "대한항공 공식 홈페이지 접근성 검수",
    id: 2,
    Html: "<div class='title'>작성중</div>",
  },
  {
    From: "KT",
    workedat: "-",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image: "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Fscreenshot04.png?alt=media&token=85d711d2-a940-4f2f-9a39-008ada095efa",
    Percentage: "10",
    Title: "K쇼핑 모바일 라이브 프로젝트",
    id: 3,
     Html: "<div class='title'>작성중</div>",
  },
  {
    From: "참좋은여행",
    workedat: "참좋은여행",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image: "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Fscreenshot05.png?alt=media&token=889624b2-30c0-4306-8018-31d12269231a",
    Percentage: "10",
    Title: "참좋은여행 개편 프로젝트",
    id: 4,
  },
  {
    From: "참좋은여행",
    workedat: "참좋은여행",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image: "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Fscreenshot05.png?alt=media&token=889624b2-30c0-4306-8018-31d12269231a",
    Percentage: "10",
    Title: "참좋은여행 운영 유지보수",
    id: 5,
  },
  {
    From: "파고다 차이랑",
    workedat: "제이브릭스",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image: "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Fscreenshot06.png?alt=media&token=22825330-86c7-4620-9b54-71524f2aa563",
    Percentage: "100",
    Title: "파고다 차이랑 브랜드 웹사이트 구축",
    id: 6,
  },
  {
    From: "The Born",
    workedat: "제이브릭스",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image: "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Fscreenshot07.png?alt=media&token=3c40247b-d0ba-462c-b4ed-5cfea5cf0cbc",
    Percentage: "100",
    Title: "더본 글로벌 웹사이트 구축",
    id: 7,
  },
  {
    From: "The Born",
    workedat: "제이브릭스",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image: "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Fscreenshot08.png?alt=media&token=2f0eb8dc-86f2-42f6-96bc-0035d91424ec",
    Percentage: "100",
    Title: "원조쌈밥 웹사이트 구축",
    id: 8,
  },
  {
    From: "The Born",
    workedat: "제이브릭스",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image: "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Fscreenshot09.png?alt=media&token=bda5a130-16d1-480b-a0b6-75b00b75dd25",
    Percentage: "100",
    Title: "빽스비어 웹사이트 구축",
    id: 9,
  },
  {
    From: "한컴GMD",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image:
      "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Ferror.svg?alt=media&token=f65bad2a-db23-498a-bd4a-0e674ba82416",
    Percentage: "100",
    Title: "한컴GMD 모바일 포렌식 다국어 웹사이트 제작",
    id: 10,
  },
  {
    From: "지니언스",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image:
      "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Ferror.svg?alt=media&token=f65bad2a-db23-498a-bd4a-0e674ba82416",
    Percentage: "100",
    Title: "지니언스 반응형 웹사이트 제작",
    id: 11,
  },
  {
    From: "KINX",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image: "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Fscreenshot11.png?alt=media&token=e90edc5b-7cf4-448d-ae47-f456328b801d",
    Percentage: "100",
    Title: "KINX 반응형 웹사이트 제작",
    id: 12,
  },
  {
    From: "서울대학교",
    Hash: ["반응형", "Html", "Css", "jQuery"],
    Image:
      "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Ferror.svg?alt=media&token=f65bad2a-db23-498a-bd4a-0e674ba82416",
    Percentage: "100",
    Title: "서울대학교 DTM 공식 홈페이지 구축",
    id: 13,
  },
  // {
  //   From: "몽키랩",
  //   Hash: ["반응형", "Html", "Css", "jQuery"],
  //   Image:
  //     "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Ferror.svg?alt=media&token=f65bad2a-db23-498a-bd4a-0e674ba82416",
  //   Percentage: "100",
  //   Title: "오디너리 매거진",
  //   id: 13,
  // },
  // {
  //   From: "몽키랩",
  //   Hash: ["반응형", "Html", "Css", "jQuery"],
  //   Image:
  //     "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Ferror.svg?alt=media&token=f65bad2a-db23-498a-bd4a-0e674ba82416",
  //   Percentage: "100",
  //   Title: "런시티",
  //   id: 14,
  // },
  // {
  //   From: "솔트 엔터테인먼트",
  //   Hash: ["반응형", "Html", "Css", "jQuery"],
  //   Image:
  //     "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Ferror.svg?alt=media&token=f65bad2a-db23-498a-bd4a-0e674ba82416",
  //   Percentage: "100",
  //   Title: "솔트 엔터테인먼트",
  //   id: 16,
  // },
  // {
  //   From: "더좋은이엔티",
  //   Hash: ["반응형", "Html", "Css", "jQuery"],
  //   Image:
  //     "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Ferror.svg?alt=media&token=f65bad2a-db23-498a-bd4a-0e674ba82416",
  //   Percentage: "100",
  //   Title: "더좋은이엔티",
  //   id: 17,
  // },
  // {
  //   From: "대명문화공장",
  //   Hash: ["반응형", "Html", "Css", "jQuery"],
  //   Image:
  //     "https://firebasestorage.googleapis.com/v0/b/swvuefolio.appspot.com/o/portfolios%2Ferror.svg?alt=media&token=f65bad2a-db23-498a-bd4a-0e674ba82416",
  //   Percentage: "100",
  //   Title: "대명문화공장 웹사이트 구축 및 유지보수",
  //   id: 18,
  // },
];
